"""
@module: equity.diagnostics.lookahead_indicator
@depends: pandas, numpy
@exports: run_lookahead_indicator, main
@paper_ref: docs/plan/2026-07-27_trading_forecaster_prd.md §6.4.1
@data_flow: features frame + prices -> per-indicator recompute from prices[:t]
            -> assert equality with stored feature -> JSON report

Lookahead indicator diagnostic guard (S3.3). For each indicator feature column
``f`` and each row at time ``t``, recompute ``f(t)`` from ``prices[:t]`` ONLY
(the frame sliced to rows strictly before ``t`` within the same ticker group)
and assert numerical equality with the stored feature within float64 tolerance
(``abs=1e-9``).

The leak this guard catches (FOOTGUN #1, PRD §6.4.1): an SMA window that
INCLUDES ``close[t]`` (forgot ``closed='left'`` or ``.shift(1)``). The naive
violation injection in tests uses exactly this -- an SMA built with
``closed='right'`` (the pandas default) instead of the past-only form.

Coverage (round-1 review fix, BLOCKER 1): the guard checks the technical
indicator columns from :data:`equity.features.technical.NAIVE_INDICATOR_SPECS`
AND lag-layer columns whose base exists in ``prices`` (e.g. ``close_lag1``,
``close_rollmean3``). Lag specs are auto-generated by parsing the
``_lag{N}`` / ``_rollmean{N}`` / ``_rollstd{N}`` suffix off feature columns.
LIMITATION: lag features whose base is NOT a price column (e.g.
``sma_5_lag1``, ``sentiment_score_rollmean3``) are NOT covered -- the spec
callable only sees the prices frame, so it cannot recompute a non-price base.
Cover the price-derived lag bases fully (the invariant-critical case); document
the sentiment/technical-lag limitation here. Add coverage for those later by
extending the spec builder to consume the features frame too.

NaN handling (D5): NaN in early rolling windows (warmup) is "undefined at this
row", NOT a violation. The guard skips rows where either the stored value or
the re-derived value is NaN. A row where exactly one of (stored, re-derived)
is NaN and the other is finite is a violation (a partial-window bug).

Generic recompute core (D3): the guard takes a ``column_specs`` parameter --
a mapping ``{feature_col: per-ticker single-ticker spec fn}`` where each fn
takes a single-ticker prices frame (sorted ascending by ``period_close_ts``)
and returns the NAIVE (current-row-inclusive) indicator Series. The guard feeds
``prices[:t]`` through the fn and takes the last value. Defaults to
:data:`equity.features.technical.NAIVE_INDICATOR_SPECS` (extended with the
auto-generated lag specs for price-derived lag columns) so sentiment-roll
features can be added later by extending the specs dict -- no guard rewrite.

Complexity (round-1 review fix, SUBSTANTIVE 12): the guard is O(N^2 * F) where
N = rows per ticker and F = features checked. The per-row slice + per-row spec
recompute is the dominant cost; the searchsorted lookup is O(log N) but the
spec fn itself is O(N) (rolling over the pre-slice), giving O(N^2 * F). For
large frames use ``--max-rows`` to downsample per ticker.

CLI:

    python -m equity.diagnostics.lookahead_indicator \\
        --features <features.parquet> --prices <prices.parquet> \\
        [--output <report.json>] [--strict] [--max-rows N]

Exits 0 on PASS, 1 on any violation. Mirrors the
:mod:`equity.diagnostics.sentiment_aggregate_guard` CLI shape (argparse,
``main()``, ``RESULTS_DIR = PROJECT_ROOT / "results" / "diagnostics" / "equity"``,
``_resolve_under_project_root`` containment guard).
"""

from __future__ import annotations

import argparse
import json
import re
import warnings
from pathlib import Path
from typing import Any, Callable

import numpy as np
import pandas as pd

from equity.features.technical import NAIVE_INDICATOR_SPECS

# Round-1 review fix (SUBSTANTIVE 16): decouple from equity.data.registry.
# Default project root = repo root (parents[2] of this file). ``main`` and
# ``_resolve_under_project_root`` accept an override; tests can monkeypatch
# ``PROJECT_ROOT`` (module-level) for containment checks without importing
# equity.data.registry.
PROJECT_ROOT = Path(__file__).resolve().parents[2]
RESULTS_DIR = PROJECT_ROOT / "results" / "diagnostics" / "equity"

# float64 tolerance for indicator recompute equality. Indicators like SMA/EMA
# are stable to ~1e-12; MACD has cumulative drift but stays well within 1e-9
# for the window sizes we use. Use abs=1e-9 as the PRD specifies.
_ABS_TOL = 1e-9

# Regex parsing the lag-layer suffix off a feature column name. The base is
# everything BEFORE the LAST ``_lag{N}`` / ``_rollmean{N}`` / ``_rollstd{N}``.
# Non-greedy on the digits to keep the base greedy (e.g. ``close_lag1`` ->
# base="close", kind="lag", n=1).
_LAG_SUFFIX_RE = re.compile(r"^(.*)_(lag|rollmean|rollstd)(\d+)$")


def _lag_specs_from_features(
    features: pd.DataFrame, price_cols: list[str]
) -> dict[str, Callable[[pd.DataFrame], pd.Series]]:
    """Round-1 review fix (BLOCKER 1): auto-generate per-ticker spec fns for
    lag-layer columns (``{base}_lag{N}`` / ``{base}_rollmean{N}`` /
    ``{base}_rollstd{N}``) whose ``base`` is a PRICE column (exists in
    ``price_cols``).

    Spec convention (matches :data:`equity.features.technical.NAIVE_INDICATOR_SPECS`):
    the spec fn returns the NAIVE (current-row-inclusive) form such that
    ``spec(prices[:t]).iloc[-1] == stored_feature[t]``. The guard feeds the
    prices slice ending at ``t-1`` and takes the last value, so the naive form
    at ``t-1`` must equal the stored past-only feature at ``t``:

    * ``{base}_lag{N}`` = ``base.shift(N)``  -> naive spec = ``base.shift(N-1)``
      (``base.shift(N-1)(t-1) = base(t-N) = feature(t)``).
    * ``{base}_rollmean{N}`` = ``base.rolling(N, closed='left').mean()``  ->
      naive spec = ``base.rolling(N, closed='right').mean()``
      (``naive(t-1) = mean(base[t-N..t-1]) = feature(t)``).
    * ``{base}_rollstd{N}`` = ``base.rolling(N, closed='left').std()``  ->
      naive spec = ``base.rolling(N, closed='right').std()``.

    LIMITATION: lag columns whose base is NOT a price column (technical bases
    like ``sma_5``, sentiment bases like ``sentiment_score``) are SKIPPED -- the
    spec fn only sees the prices frame and cannot recompute a non-price base.
    """
    specs: dict[str, Callable[[pd.DataFrame], pd.Series]] = {}
    price_set = set(price_cols)
    for col in features.columns:
        if not isinstance(col, str):
            continue
        m = _LAG_SUFFIX_RE.match(col)
        if m is None:
            continue
        base, kind, n_str = m.group(1), m.group(2), m.group(3)
        if base not in price_set:
            continue
        n = int(n_str)
        if kind == "lag":
            specs[col] = (lambda b, n: lambda p: p[b].shift(n - 1))(base, n)
        elif kind == "rollmean":
            specs[col] = (lambda b, n: lambda p: p[b].rolling(n, closed="right").mean())(base, n)
        elif kind == "rollstd":
            specs[col] = (lambda b, n: lambda p: p[b].rolling(n, closed="right").std())(base, n)
    return specs


def _resolve_under_project_root(path: str | Path, project_root: Path | None = None) -> Path:
    """Resolve ``--output`` safely. Mirrors the sentiment_aggregate_guard
    containment guard (refuses ``..`` traversal AND refuses absolute paths
    outside ``project_root``). See
    :func:`equity.diagnostics.sentiment_aggregate_guard._resolve_under_project_root`.

    Round-1 review fix (TRIVIAL 5): a previously-accepted absolute path
    OUTSIDE the project root is now REJECTED (the old code accepted any
    absolute path, which defeated the containment guard). Absolute paths
    INSIDE the project root still work.
    """
    root = project_root if project_root is not None else PROJECT_ROOT
    raw = Path(path)
    parts = list(raw.parts)
    if ".." in parts:
        raise ValueError(f"Refusing --output with path-traversal component '..': {path}.")
    if not raw.is_absolute():
        resolved = (root / raw).resolve()
    else:
        resolved = raw.resolve()
    # Containment: resolved must live under the project root.
    try:
        resolved.relative_to(root.resolve())
    except ValueError as exc:
        raise ValueError(f"Refusing --output outside project root ({root}): {path}.") from exc
    return resolved


def _rederive_indicator_at_t(
    spec_fn: Callable[[pd.DataFrame], pd.Series],
    prices_ticker_pre_t: pd.DataFrame,
) -> float:
    """Recompute the NAIVE indicator on ``prices_ticker_pre_t`` (a single-ticker
    prices frame containing rows strictly before ``t``) and return the LAST
    value. The past-only feature at row ``t`` is the naive value computed at
    ``t-1`` (see :mod:`equity.features.technical`); feeding ``prices[:t]``
    through the naive fn and taking the last row reproduces that exactly.

    Spec fns return a Series (the {col: Series} contract). MACD's three columns
    share a memoized spec fn (see :func:`equity.features.technical._build_naive_specs`)
    so ``_macd_naive`` runs once per row-slice, not three times.
    """
    if prices_ticker_pre_t.empty:
        return np.nan
    naive = spec_fn(prices_ticker_pre_t)
    if naive.empty:
        return np.nan
    return float(naive.iloc[-1])


def run_lookahead_indicator(
    features: pd.DataFrame,
    prices: pd.DataFrame,
    *,
    column_specs: dict[str, Callable[[pd.DataFrame], pd.Series]] | None = None,
    abs_tol: float = _ABS_TOL,
    strict: bool = False,
    max_rows: int | None = None,
) -> dict[str, Any]:
    """Run the lookahead indicator guard and return a result dict.

    Parameters
    ----------
    features:
        Feature matrix produced by :func:`equity.features.build_features` (or
        :func:`add_technical_features`). Must carry ``ticker``,
        ``period_close_ts``, and each feature column in ``column_specs``.
    prices:
        The canonical S1 prices frame used to build ``features``. Must carry
        ``ticker``, ``period_close_ts``, and the price columns each spec fn
        reads (typically ``close``, ``high``, ``low``, ``volume``).
    column_specs:
        Optional mapping ``{feature_col: per-ticker spec fn}``. Defaults to
        :data:`equity.features.technical.NAIVE_INDICATOR_SPECS` extended with
        auto-generated lag specs for price-derived lag columns (see
        :func:`_lag_specs_from_features`). Each fn takes a single-ticker
        prices frame (sorted ascending by ``period_close_ts``) and returns the
        NAIVE (current-row-inclusive) indicator Series.
    abs_tol:
        Absolute tolerance for float64 equality (default ``1e-9``).
    strict:
        Round-1 review fix (SUBSTANTIVE 11). When True, raise ``ValueError`` if
        any spec column is MISSING from ``features.columns`` (default: silently
        omit). Use in CI to catch a feature block that silently dropped a column.
    max_rows:
        Round-1 review fix (SUBSTANTIVE 12). When set, downsample ``prices``
        and ``features`` to the first ``max_rows`` rows per ticker (after the
        per-ticker ascending sort). Emits a warning when truncation occurs.
        Bounds the O(N^2 * F) cost for large frames.

    Returns
    -------
    dict
        ``{pass, n_violations, violations, n_rows, n_features_checked, ...}``.

    Complexity
    ----------
    O(N^2 * F) where N = rows per ticker, F = features checked. The per-row
    spec recompute is O(N) (rolling over the pre-slice); the outer per-row loop
    is O(N), giving O(N^2) per ticker. Use ``max_rows`` to bound N.
    """
    specs = dict(column_specs) if column_specs is not None else dict(NAIVE_INDICATOR_SPECS)
    if column_specs is None:
        # Round-1 review fix (BLOCKER 1): merge in auto-generated lag specs for
        # price-derived lag columns present in the features frame.
        specs.update(_lag_specs_from_features(features, list(prices.columns)))

    violations: list[dict[str, Any]] = []

    if "ticker" not in features.columns or "period_close_ts" not in features.columns:
        raise ValueError(
            "run_lookahead_indicator: features frame must have 'ticker' and 'period_close_ts' columns."
        )
    if "ticker" not in prices.columns or "period_close_ts" not in prices.columns:
        raise ValueError(
            "run_lookahead_indicator: prices frame must have 'ticker' and 'period_close_ts' columns."
        )

    # Round-1 review fix (SUBSTANTIVE 11): strict mode -- refuse missing spec
    # columns instead of silently omitting them.
    missing_spec_cols = set(specs) - set(features.columns)
    if strict and missing_spec_cols:
        raise ValueError(
            "run_lookahead_indicator: strict mode -- spec columns missing from "
            f"features: {sorted(missing_spec_cols)}."
        )

    # Pre-sort prices per ticker ascending by period_close_ts. The recompute
    # core slices ``prices[:t]`` per row, so we need O(log N) lookup by ts.
    prices_sorted = prices.sort_values(["ticker", "period_close_ts"]).reset_index(drop=True)
    # Build per-ticker (timestamp -> integer position in the sorted ticker
    # sub-frame) for O(1) "rows strictly before t" slicing.
    price_groups = {
        t: g.reset_index(drop=True) for t, g in prices_sorted.groupby("ticker", sort=False)
    }

    # Round-1 review fix (SUBSTANTIVE 12): optional per-ticker downsampling.
    if max_rows is not None and max_rows > 0:
        truncated_groups: list[pd.DataFrame] = []
        truncated = 0
        for t, g in price_groups.items():
            if len(g) > max_rows:
                truncated += len(g) - max_rows
                g = g.iloc[:max_rows]
            truncated_groups.append(g)
        price_groups = {g["ticker"].iloc[0]: g.reset_index(drop=True) for g in truncated_groups}
        if truncated > 0:
            warnings.warn(
                f"run_lookahead_indicator: --max-rows={max_rows} truncated "
                f"{truncated} price rows across tickers.",
                stacklevel=2,
            )

    # We re-derive by row position within the ticker group. The "rows strictly
    # before t" slice is rows with period_close_ts < t. Find the largest
    # position whose ts < t.
    def _rows_strictly_before(ticker: str, ts: pd.Timestamp) -> pd.DataFrame:
        g = price_groups.get(ticker)
        # Round-1 review fix (TRIVIAL 2): g is None here -> the old ternary
        # ``pd.DataFrame(columns=g.columns) if g is not None else pd.DataFrame()``
        # always took the else branch AND would have crashed on ``g.columns``
        # when g is None. Simplify to the empty frame.
        if g is None:
            return pd.DataFrame()
        # Use searchsorted on the sorted ts column.
        ts_col = g["period_close_ts"]
        # searchsorted(side='left') returns the first index >= ts.
        idx = ts_col.searchsorted(ts, side="left")
        return g.iloc[:idx]

    # Restrict to feature columns actually present in the features frame.
    feature_cols_to_check = [c for c in specs if c in features.columns]
    n_rows_checked = 0
    n_violations = 0

    for ticker, g in features.groupby("ticker", sort=False):
        # Sort the feature group by period_close_ts to align with prices.
        g_sorted = g.sort_values("period_close_ts")
        # Round-1 review fix (SUBSTANTIVE 12): apply max_rows to features too.
        if max_rows is not None and max_rows > 0 and len(g_sorted) > max_rows:
            g_sorted = g_sorted.iloc[:max_rows]
        # Round-1 review fix (TRIVIAL 6): itertuples() is materially faster
        # than iterrows() (no Series construction per row). index=False keeps
        # the row as a plain namedtuple (positional access by column order).
        # Build a column-index map so we can fetch by name from the namedtuple.
        col_index = {c: i for i, c in enumerate(g_sorted.columns)}
        fcol_indices = [(c, col_index[c]) for c in feature_cols_to_check if c in col_index]
        ts_idx = col_index["period_close_ts"]
        for row in g_sorted.itertuples(index=False):
            ts = row[ts_idx]
            # Canonicalize tz for the comparison -- prices may be America/New_York
            # while features may be UTC (build_features canonicalizes). Convert
            # both to UTC for the searchsorted lookup.
            ts_for_lookup = ts
            price_g = price_groups.get(ticker)
            if price_g is None or price_g.empty:
                continue
            price_ts = price_g["period_close_ts"]
            # Convert both to UTC for the lookup if tz-aware.
            if price_ts.dt.tz is not None and ts_for_lookup.tz is not None:
                if price_ts.dt.tz != ts_for_lookup.tz:
                    ts_for_lookup = ts_for_lookup.tz_convert(price_ts.dt.tz)
            pre = _rows_strictly_before(ticker, ts_for_lookup)
            n_rows_checked += 1
            for fcol, fi in fcol_indices:
                stored_val = row[fi]
                spec_fn = specs[fcol]
                rederived = _rederive_indicator_at_t(spec_fn, pre)
                _record = _compare_values(
                    ticker, ts, fcol, stored_val, rederived, abs_tol, violations
                )
                if _record is not None:
                    n_violations += _record

    return {
        "pass": n_violations == 0,
        "n_violations": n_violations,
        "violations": violations,
        "n_rows_checked": n_rows_checked,
        "n_features_checked": len(feature_cols_to_check),
        "features_checked": feature_cols_to_check,
        "abs_tol": float(abs_tol),
        "max_rows": max_rows,
    }


def _compare_values(
    ticker: str,
    ts: Any,
    fcol: str,
    stored_val: Any,
    rederived: float,
    abs_tol: float,
    violations: list[dict[str, Any]],
) -> int | None:
    """Compare stored vs re-derived and append a violation record on mismatch.
    Returns 1 if a violation was appended, 0 if the row was a clean match,
    None if the row was skipped (both NaN). NaN handling per D5: both NaN =
    "undefined at this row" -> skip; exactly one NaN = partial-window bug.
    """
    if pd.isna(stored_val) and pd.isna(rederived):
        return None
    if pd.isna(stored_val) != pd.isna(rederived):
        violations.append(
            {
                "type": "lookahead_nan_mismatch",
                "ticker": ticker,
                "period_close_ts": str(ts),
                "feature": fcol,
                "stored": None if pd.isna(stored_val) else float(stored_val),
                "rederived": None if pd.isna(rederived) else float(rederived),
            }
        )
        return 1
    diff = abs(float(stored_val) - float(rederived))
    if diff > abs_tol:
        violations.append(
            {
                "type": "lookahead_indicator_mismatch",
                "ticker": ticker,
                "period_close_ts": str(ts),
                "feature": fcol,
                "stored": float(stored_val),
                "rederived": float(rederived),
                "abs_diff": float(diff),
                "tol": float(abs_tol),
            }
        )
        return 1
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(
        description=(
            "Lookahead indicator guard (S3.3): recomputes each technical "
            "indicator from prices[:t] only and asserts equality with the "
            "stored feature. Catches SMA/EMA/RSI/etc. windows that include "
            "the current row (forgot closed='left' or .shift(1)). Exits 0 on "
            "PASS, 1 on any violation."
        ),
    )
    parser.add_argument(
        "--features",
        required=True,
        help="Path to the feature matrix parquet (output of build_features).",
    )
    parser.add_argument(
        "--prices",
        required=True,
        help="Path to the canonical S1 prices parquet used to build the features.",
    )
    parser.add_argument(
        "--abs-tol",
        type=float,
        default=_ABS_TOL,
        help=f"Absolute tolerance for float64 equality (default {_ABS_TOL}).",
    )
    parser.add_argument(
        "--output",
        help="Optional path to write the JSON result (resolved under PROJECT_ROOT).",
    )
    parser.add_argument(
        "--strict",
        action="store_true",
        help=(
            "SUBSTANTIVE 11: raise on missing spec columns instead of silently "
            "omitting them. Use in CI to catch a feature block that dropped a column."
        ),
    )
    parser.add_argument(
        "--max-rows",
        type=int,
        default=None,
        help=(
            "SUBSTANTIVE 12: downsample prices/features to the first N rows per "
            "ticker (after the per-ticker ascending sort). Bounds the O(N^2*F) cost."
        ),
    )
    args = parser.parse_args()

    features = pd.read_parquet(args.features)
    prices = pd.read_parquet(args.prices)

    result = run_lookahead_indicator(
        features,
        prices,
        abs_tol=args.abs_tol,
        strict=args.strict,
        max_rows=args.max_rows,
    )

    RESULTS_DIR.mkdir(parents=True, exist_ok=True)
    if args.output:
        out_path = _resolve_under_project_root(args.output)
    else:
        ts = pd.Timestamp.now(tz="UTC").strftime("%Y%m%dT%H%M%SZ")
        out_path = RESULTS_DIR / f"lookahead_indicator_{ts}.json"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(json.dumps(result, indent=2), encoding="utf-8")

    print(json.dumps(result, indent=2))
    print(f"\nResult written to: {out_path}")
    return 0 if result["pass"] else 1


if __name__ == "__main__":
    raise SystemExit(main())
